// Auto-generated by typescript-scss-modules
declare const styles: {
  readonly checkboxContainer: string;
  readonly animating: string;
  readonly checkboxWrapper: string;
  readonly correctionCheckbox: string;
  readonly checkIcon: string;
  readonly checkMarkIcon: string;
  readonly labelContainer: string;
  readonly fieldLabel: string;
  readonly correctedBadge: string;
  readonly badgeIcon: string;
  readonly badgeText: string;
  readonly pending: string;
  readonly corrected: string;
};

export = styles;
